In [1]:
# interger type
income = 2000
# flot type
additional_income = 200.0
total = income + additional_income
print(total)
print(type(total))

2200.0
<class 'float'>


Explicit Conversion :

In [2]:
price = 10000
tax = '20'
total_cost = price + int(tax)
print(total_cost)

10020


In [3]:
# Type casting : 
income = 10000.45
print(int(income))

10000


In [4]:
# float conversion type casting:
income = 4000
print(float(income))
price = 34.5
print(str(price))

4000.0
34.5


In [5]:
price = 34.5
print(str(price))

34.5


In [6]:
print(type(price))

<class 'float'>


In [8]:
x = 10
# x is equal to 10
print(bool(x))


True


In [10]:
y=2
y != 10 # x is not equal to 10
print(bool(y))

True


In [12]:
# Concat: 
'abc'+' '+ 'cbe'


'abc cbe'

In [13]:
string = 'india'
len(string)

5

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

Write a Numpy Program to Create a 4 X 4 array with random values, now create a new array from the said array such that it starts with the Last Row and Goes till the end

In [17]:
import numpy as np
num = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(num,"\n")
print("New array starts with the Last Row:")
nums[::-1]=nums[::-1]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

New array starts with the Last Row:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


#WAP to calculate the factorial of a number. Factorial of any number n is (n)*(n-1)*(n-2)....*1 and written as (n!) and read as 'n factorial'. For example :
Bhuvanesh Chellapandian3:37 PM
4! = 4*3*2*1 = 24, 3! = 3*2*1 = 6, 2! = 2*1=2, 1! = 1 and Also 0! = 1. Lets code to calculate the Factorial of a Number by using Define Function

In [13]:
def factorial(num):
    if num==0:
        return 1
    else:
        for i in range(1,num+1):
            fact=1
            fact=fact*i
            return fact
num=int(input("enter:"))
factorial(num)
        


enter:4


1

In [16]:
def factorial(n):
    if n == 0:
        return 1
    fact = 1
    for i in range(1, n+1):
        fact = fact * i
    return fact
num=int(input("enter a number:"))
factorial(num)

enter a number:3


6

In [23]:
import random
import numpy as np
array=np.random.randint(20,size=(4,4))
print(array,"\n")
new_array=array[::-1]
print("reshaped array:\n",new_array)

[[11  9 12 14]
 [15 19 11 18]
 [ 4 15 14 11]
 [19 10  4 13]] 

reshaped array:
 [[19 10  4 13]
 [ 4 15 14 11]
 [15 19 11 18]
 [11  9 12 14]]


In [1]:
# calculation by using input keyword:
a = int(input('Enter a Number : '))
b = int(input('Enter a Number : '))
c = a + b
print(c)

Enter a Number : 5
Enter a Number : 4
9


In [2]:
weight = int(input('Enter a weight - '))
height = float(input('Enter a Height - '))
BMI = round(weight / (height**2), 5)
print('Body Mass Index - ', BMI)

Enter a weight - 38
Enter a Height - 145
Body Mass Index -  0.00181


In [4]:
# Assignment : 
#calculate principle, Tenure and Rate of Interest
#output should be calculation of my simple interest. 
P=int(input("enter a value:"))
T=int(input("enter a value:"))
R=float(input("enter a value:"))
Simple_interest = P*T*R/100
print(Simple_interest)

enter a value:23
enter a value:78
enter a value:2
35.88


Day - 04 :

In [7]:
# Concat : 
print('Hello', 'How Are You', sep = ' ' )

Hello How Are You


In [8]:
print('Hello World')
print('\n')
print('How Are You')

Hello World


How Are You


In [9]:
print('What is your' + str(35))

What is your35


# Python Operators : 
Addition
Subraction
Division
Multiplication
Modulus
Square

In [10]:
# Adding Two String: 
first_name = 'Mike'
last_name = 'Anderson'
# Assigning A Simple Variable: 
full_name = first_name + last_name
print(full_name)

MikeAnderson


In [11]:
text = 'Age is 25'
age = '22'
combine = text + age
print(combine)

Age is 2522


In [12]:
price = 120
discount = 35.5
net_price = price - discount
print(net_price)

84.5


In [13]:
price = 120
quantity = 15
total_cost = price * quantity
print(total_cost)

1800


In [14]:
value = 'India'
count = 3
result = value * count
print(result)

IndiaIndiaIndia


In [15]:
total_cost = 13000
quantity = 23
price_per_unit = total_cost // quantity
print(price_per_unit)
# // - division
# / - remainder of the Division

565


In [16]:
# % - Reaminder of the Division : 
 
total_cost = 2700
quantity = 23
price_per_unit = total_cost % quantity
print(price_per_unit)

9


In [17]:
# power input : 
value = 2 
n = 3
result = value ** n
print(result)

8


In [18]:
# how will You Prove John's Age is Greater than my Age by using Python Coding.
my_age = 23
john_age = 25
my_age > john_age

False

In [19]:
my_age < john_age

True

In [20]:
my_age == john_age

False

In [21]:
my_age >= john_age

False

In [22]:
my_age != john_age

True

In [23]:
# Membership Operators : 
string = 'Hello World'
var = 'o'
print(var in string)

True


In [6]:
me="xyz"
if(me=="Xyz"): print("You are welcome to become a Prepster.") 

#Short hand if-else statement
me="Prepster"
print("You are welcome to become a Prepster") if(me=="Xyz") else print("Welcome To PrepInsta")

Welcome To PrepInsta


In [7]:
me="roja"
print("welcome") if(me=='roja')else print("not welcome!")

welcome


In [8]:
name=['r','o','j','a']
for i in name:
    print(i,end=" ")

r o j a 

In [11]:
a=10
b=20
print("a={} and b={}".format(a,b))

a=10 and b=20


In [10]:
i,n=0,5
while(i<n):
    j=0
    while(j<n):
        print("*",end=" ")
        j+=1
    i+=1
    print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 
